### ISSUE TITLE
ARM/ARM64 version?

### ISSUE THREAD

**Issue by bremaya** [dgilman/aacgain#4]
It's possible to compile an version ARM/ARM64 to use in Android with termux? Thanks for this great job!

**Comment by dgilman** [comment]
I'm not opposed to this, I just don't know anything about building for Android. I could build a random ARM binary but that probably would not be particularly useful for you. If you can find appropriate examples/tutorials of how they are built with cmake I can add it to CI.

**Comment by bremaya** [comment]
I'm not sure if this is useful for compile a apropriete binary:
https://wiki.termux.com/wiki/Building_packages
Thanks for yor time man!

**Comment by dgilman** [comment]
It looks like termux is a package manager, you want to do the packaging in this repo https://github.com/termux/termux-packages
